/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardJobsRouteImport } from './routes/dashboard/jobs'
import { Route as DashboardExchangeRouteImport } from './routes/dashboard/exchange'
import { Route as DashboardConnectorsRouteImport } from './routes/dashboard/connectors'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardTicketsIndexRouteImport } from './routes/dashboard/tickets/index'
import { Route as DashboardOrgsIndexRouteImport } from './routes/dashboard/orgs/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardTicketsTicketIdRouteImport } from './routes/dashboard/tickets/$ticketId'
import { Route as DashboardOrgsOrgIdRouteImport } from './routes/dashboard/orgs/$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExchangeRoute = DashboardExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConnectorsRoute = DashboardConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsIndexRoute = DashboardTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrgsIndexRoute = DashboardOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTicketsTicketIdRoute =
  DashboardTicketsTicketIdRouteImport.update({
    id: '/tickets/$ticketId',
    path: '/tickets/$ticketId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrgsOrgIdRoute = DashboardOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/tickets': typeof DashboardTicketsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/tickets': typeof DashboardTicketsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/connectors': typeof DashboardConnectorsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orgs/$orgId': typeof DashboardOrgsOrgIdRoute
  '/dashboard/tickets/$ticketId': typeof DashboardTicketsTicketIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/dashboard/orgs/': typeof DashboardOrgsIndexRoute
  '/dashboard/tickets/': typeof DashboardTicketsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/connectors'
    | '/dashboard/exchange'
    | '/dashboard/jobs'
    | '/dashboard/'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/orgs'
    | '/dashboard/tickets'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/connectors'
    | '/dashboard/exchange'
    | '/dashboard/jobs'
    | '/dashboard'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/orgs'
    | '/dashboard/tickets'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/connectors'
    | '/dashboard/exchange'
    | '/dashboard/jobs'
    | '/dashboard/'
    | '/dashboard/orgs/$orgId'
    | '/dashboard/tickets/$ticketId'
    | '/dashboard/users/$userId'
    | '/dashboard/orgs/'
    | '/dashboard/tickets/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/exchange': {
      id: '/dashboard/exchange'
      path: '/exchange'
      fullPath: '/dashboard/exchange'
      preLoaderRoute: typeof DashboardExchangeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/connectors': {
      id: '/dashboard/connectors'
      path: '/connectors'
      fullPath: '/dashboard/connectors'
      preLoaderRoute: typeof DashboardConnectorsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/': {
      id: '/dashboard/tickets/'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/': {
      id: '/dashboard/orgs/'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tickets/$ticketId': {
      id: '/dashboard/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/dashboard/tickets/$ticketId'
      preLoaderRoute: typeof DashboardTicketsTicketIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orgs/$orgId': {
      id: '/dashboard/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/dashboard/orgs/$orgId'
      preLoaderRoute: typeof DashboardOrgsOrgIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConnectorsRoute: typeof DashboardConnectorsRoute
  DashboardExchangeRoute: typeof DashboardExchangeRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrgsOrgIdRoute: typeof DashboardOrgsOrgIdRoute
  DashboardTicketsTicketIdRoute: typeof DashboardTicketsTicketIdRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardOrgsIndexRoute: typeof DashboardOrgsIndexRoute
  DashboardTicketsIndexRoute: typeof DashboardTicketsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConnectorsRoute: DashboardConnectorsRoute,
  DashboardExchangeRoute: DashboardExchangeRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrgsOrgIdRoute: DashboardOrgsOrgIdRoute,
  DashboardTicketsTicketIdRoute: DashboardTicketsTicketIdRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardOrgsIndexRoute: DashboardOrgsIndexRoute,
  DashboardTicketsIndexRoute: DashboardTicketsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
