use axum::{middleware, routing::get, Router};
use imperium_infra::{
    telemetry::{http_metrics_middleware, request_id_middleware},
    SharedAppState,
};
use tower_http::trace::TraceLayer;

pub fn build_router(state: SharedAppState) -> Router {
    Router::new()
        .route("/health", get(crate::routes::system::health))
        .route("/ready", get(crate::routes::system::ready))
        .route(
            "/api/v1/imperium/health",
            get(crate::routes::system::health),
        )
        .route("/api/v1/imperium/ready", get(crate::routes::system::ready))
        .route("/api/v1/imperium/meta", get(crate::routes::system::meta))
        .route(
            "/api/v1/imperium/providers",
            get(crate::routes::system::providers),
        )
        .route(
            "/api/v1/imperium/providers/health",
            get(crate::routes::system::providers_health),
        )
        .route(
            "/api/v1/imperium/openapi.json",
            get(crate::routes::system::openapi_document),
        )
        .route("/metrics", get(crate::routes::system::metrics))
        .route(
            "/api/v1/imperium/metrics",
            get(crate::routes::system::metrics),
        )
        .route(
            "/api/v1/imperium/ops/dlq",
            get(crate::routes::system::dead_letter_queue),
        )
        .route(
            "/api/v1/imperium/ops/dlq/{event_id}/replay",
            axum::routing::post(crate::routes::system::replay_dead_letter),
        )
        .route(
            "/api/v1/imperium/ops/audit",
            get(crate::routes::system::audit_events),
        )
        .route(
            "/api/v1/imperium/auth/session/token",
            axum::routing::post(crate::routes::auth::issue_session_token),
        )
        .route(
            "/api/v1/imperium/auth/session/refresh",
            axum::routing::post(crate::routes::auth::refresh_session_token),
        )
        .route(
            "/api/v1/imperium/auth/session/revoke",
            axum::routing::post(crate::routes::auth::revoke_session_token),
        )
        .route(
            "/api/v1/imperium/auth/passkeys/challenge",
            axum::routing::post(crate::routes::auth::passkey_challenge),
        )
        .route(
            "/api/v1/imperium/auth/apple/verify",
            axum::routing::post(crate::routes::auth::verify_apple_identity),
        )
        .route(
            "/api/v1/imperium/markets/watchlist",
            axum::routing::get(crate::routes::markets::watchlist)
                .post(crate::routes::markets::add_watchlist_entry),
        )
        .route(
            "/api/v1/imperium/markets/watchlist/{symbol}",
            axum::routing::delete(crate::routes::markets::remove_watchlist_entry),
        )
        .route(
            "/api/v1/imperium/markets/{symbol}/quote",
            get(crate::routes::markets::quote),
        )
        .route(
            "/api/v1/imperium/markets/{symbol}/candles",
            get(crate::routes::markets::candles),
        )
        .route(
            "/api/v1/imperium/markets/stream/contracts",
            get(crate::routes::markets::stream_contracts),
        )
        .route(
            "/api/v1/imperium/markets/stream/sse",
            get(crate::routes::markets::stream_sse),
        )
        .route(
            "/api/v1/imperium/intelligence/inbox",
            get(crate::routes::intelligence::inbox),
        )
        .route(
            "/api/v1/imperium/intelligence/clusters",
            get(crate::routes::intelligence::clusters),
        )
        .route(
            "/api/v1/imperium/intelligence/ingest/preview",
            axum::routing::post(crate::routes::intelligence::ingest_preview),
        )
        .route(
            "/api/v1/imperium/brief/today",
            get(crate::routes::brief::today),
        )
        .route(
            "/api/v1/imperium/brief/preview",
            axum::routing::post(crate::routes::brief::preview),
        )
        .route(
            "/api/v1/imperium/brief/since-last",
            get(crate::routes::brief::since_last),
        )
        .route(
            "/api/v1/imperium/portfolio/overview",
            get(crate::routes::portfolio::overview),
        )
        .route(
            "/api/v1/imperium/portfolio/accounts",
            get(crate::routes::portfolio::accounts),
        )
        .route(
            "/api/v1/imperium/portfolio/scenario/simulate",
            axum::routing::post(crate::routes::portfolio::simulate_scenario),
        )
        .route(
            "/api/v1/imperium/business/overview",
            get(crate::routes::business::overview),
        )
        .route(
            "/api/v1/imperium/business/metrics",
            get(crate::routes::business::metrics),
        )
        .route(
            "/api/v1/imperium/business/anomalies",
            get(crate::routes::business::anomalies),
        )
        .route(
            "/api/v1/imperium/alerts/rules",
            get(crate::routes::alerts::rules),
        )
        .route(
            "/api/v1/imperium/alerts/feed",
            get(crate::routes::alerts::feed),
        )
        .route(
            "/api/v1/imperium/alerts/simulate",
            axum::routing::post(crate::routes::alerts::simulate),
        )
        .route(
            "/api/v1/imperium/alerts/stream/sse",
            get(crate::routes::alerts::stream_sse),
        )
        .route(
            "/api/v1/imperium/risk/regime",
            get(crate::routes::risk::regime),
        )
        .route(
            "/api/v1/imperium/risk/indicators",
            get(crate::routes::risk::indicators),
        )
        .route(
            "/api/v1/imperium/risk/signals",
            get(crate::routes::risk::signals),
        )
        .route(
            "/api/v1/imperium/risk/scenario/preview",
            axum::routing::post(crate::routes::risk::scenario_preview),
        )
        .route(
            "/api/v1/imperium/journal/theses",
            axum::routing::get(crate::routes::journal::theses)
                .post(crate::routes::journal::create_thesis),
        )
        .route(
            "/api/v1/imperium/journal/theses/{thesis_id}/archive",
            axum::routing::post(crate::routes::journal::archive_thesis),
        )
        .route(
            "/api/v1/imperium/journal/playbooks",
            axum::routing::get(crate::routes::journal::playbooks)
                .post(crate::routes::journal::create_playbook),
        )
        .route(
            "/api/v1/imperium/journal/playbooks/{playbook_id}/toggle",
            axum::routing::post(crate::routes::journal::toggle_playbook),
        )
        .route(
            "/api/v1/imperium/journal/reminders",
            get(crate::routes::journal::reminders),
        )
        .layer(middleware::from_fn(request_id_middleware))
        .layer(middleware::from_fn(http_metrics_middleware))
        .layer(TraceLayer::new_for_http())
        .with_state(state)
}
