use crate::routes::{
    AddWatchlistEntryRequest, AlertEventView, AlertRuleView, AlertSimulationRequest,
    AlertSimulationResponse, ApiAuditEventsResponse, ApiDeadLetterResponse, ApiHealthResponse,
    ApiMetaResponse, ApiProvidersHealthResponse, ApiProvidersResponse, ApiReadinessResponse,
    AppleVerifyRequest, AppleVerifyResponse, AuditEventView, BriefCitationView, BriefClaimView,
    BriefPreviewRequest, BriefSectionView, BusinessAnomalyView, BusinessMetricView,
    BusinessOverviewView, CandleView, CreatePlaybookRequest, CreateThesisRequest, DailyBriefView,
    DeadLetterEventView, ExposureView, InboxItemView, IngestPreviewRequest, IngestPreviewResponse,
    IssueSessionRequest, IssueSessionResponse, MacroIndicatorView, MarketQuoteView,
    MarketWatchlistItemView, PasskeyChallengeRequest, PasskeyChallengeResponse, PlaybookView,
    PortfolioAccountView, PortfolioOverviewView, PortfolioPositionView, ProviderConfigView,
    ProviderHealthView, RefreshSessionRequest, RefreshSessionResponse, RegimeStateView,
    ReminderView, ReplayDeadLetterResponse, RevokeSessionRequest, RiskSignalView,
    ScenarioPreviewRequest, ScenarioPreviewResponse, ScenarioRequest, ScenarioResponse,
    SinceLastView, StoryClusterView, StreamContractView, ThesisMutationResponse, ThesisView,
    TogglePlaybookRequest, WatchlistMutationResponse,
};
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::system::health,
        crate::routes::system::ready,
        crate::routes::system::meta,
        crate::routes::system::providers,
        crate::routes::system::providers_health,
        crate::routes::system::openapi_document,
        crate::routes::system::metrics,
        crate::routes::system::dead_letter_queue,
        crate::routes::system::replay_dead_letter,
        crate::routes::system::audit_events,
        crate::routes::auth::issue_session_token,
        crate::routes::auth::refresh_session_token,
        crate::routes::auth::revoke_session_token,
        crate::routes::auth::passkey_challenge,
        crate::routes::auth::verify_apple_identity,
        crate::routes::markets::watchlist,
        crate::routes::markets::add_watchlist_entry,
        crate::routes::markets::remove_watchlist_entry,
        crate::routes::markets::quote,
        crate::routes::markets::candles,
        crate::routes::markets::stream_contracts,
        crate::routes::markets::stream_sse,
        crate::routes::intelligence::inbox,
        crate::routes::intelligence::clusters,
        crate::routes::intelligence::ingest_preview,
        crate::routes::brief::today,
        crate::routes::brief::preview,
        crate::routes::brief::since_last,
        crate::routes::portfolio::overview,
        crate::routes::portfolio::accounts,
        crate::routes::portfolio::simulate_scenario,
        crate::routes::business::overview,
        crate::routes::business::metrics,
        crate::routes::business::anomalies,
        crate::routes::alerts::rules,
        crate::routes::alerts::feed,
        crate::routes::alerts::simulate,
        crate::routes::alerts::stream_sse,
        crate::routes::risk::regime,
        crate::routes::risk::indicators,
        crate::routes::risk::signals,
        crate::routes::risk::scenario_preview,
        crate::routes::journal::theses,
        crate::routes::journal::create_thesis,
        crate::routes::journal::archive_thesis,
        crate::routes::journal::playbooks,
        crate::routes::journal::create_playbook,
        crate::routes::journal::toggle_playbook,
        crate::routes::journal::reminders
    ),
    components(
        schemas(
            ApiHealthResponse,
            ApiMetaResponse,
            ApiProvidersResponse,
            ApiProvidersHealthResponse,
            ApiReadinessResponse,
            ProviderConfigView,
            ProviderHealthView,
            ApiDeadLetterResponse,
            DeadLetterEventView,
            ReplayDeadLetterResponse,
            ApiAuditEventsResponse,
            AuditEventView,
            IssueSessionRequest,
            IssueSessionResponse,
            RefreshSessionRequest,
            RefreshSessionResponse,
            RevokeSessionRequest,
            PasskeyChallengeRequest,
            PasskeyChallengeResponse,
            AppleVerifyRequest,
            AppleVerifyResponse,
            AddWatchlistEntryRequest,
            MarketWatchlistItemView,
            WatchlistMutationResponse,
            MarketQuoteView,
            CandleView,
            StreamContractView,
            StoryClusterView,
            InboxItemView,
            IngestPreviewRequest,
            IngestPreviewResponse,
            BriefCitationView,
            BriefClaimView,
            BriefSectionView,
            BriefPreviewRequest,
            DailyBriefView,
            SinceLastView,
            PortfolioAccountView,
            PortfolioPositionView,
            ExposureView,
            PortfolioOverviewView,
            ScenarioRequest,
            ScenarioResponse,
            BusinessOverviewView,
            BusinessMetricView,
            BusinessAnomalyView,
            AlertRuleView,
            AlertEventView,
            AlertSimulationRequest,
            AlertSimulationResponse,
            RegimeStateView,
            MacroIndicatorView,
            RiskSignalView,
            ScenarioPreviewRequest,
            ScenarioPreviewResponse,
            CreateThesisRequest,
            ThesisView,
            ThesisMutationResponse,
            CreatePlaybookRequest,
            PlaybookView,
            TogglePlaybookRequest,
            ReminderView
        )
    ),
    tags(
        (name = "imperium", description = "Imperium API foundational routes")
    )
)]
pub struct ImperiumApiDoc;

pub fn openapi_json() -> serde_json::Value {
    serde_json::to_value(ImperiumApiDoc::openapi()).unwrap_or_else(|_| {
        serde_json::json!({
            "openapi": "3.1.0",
            "info": {
                "title": "imperium-api",
                "version": "0.1.0"
            }
        })
    })
}
