name: DroviRecorderMac
options:
  bundleIdPrefix: app.drovi
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: app.drovi.recorder.macos
    CODE_SIGN_STYLE: Automatic
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
targets:
  DroviRecorderMac:
    type: application
    platform: macOS
    sources:
      - path: .
        excludes:
          - project.yml
          - README.md
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Drovi Recorder
        NSMicrophoneUsageDescription: "Drovi needs microphone access to record meetings."
