/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AiRouteImport } from './routes/ai'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingInviteTeamRouteImport } from './routes/onboarding/invite-team'
import { Route as OnboardingCreateOrgRouteImport } from './routes/onboarding/create-org'
import { Route as OnboardingConnectSourcesRouteImport } from './routes/onboarding/connect-sources'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as DashboardTrustRouteImport } from './routes/dashboard/trust'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard/schedule'
import { Route as DashboardExchangeRouteImport } from './routes/dashboard/exchange'
import { Route as DashboardContinuumsRouteImport } from './routes/dashboard/continuums'
import { Route as DashboardConsoleRouteImport } from './routes/dashboard/console'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard/builder'
import { Route as DashboardActuationsRouteImport } from './routes/dashboard/actuations'
import { Route as DashboardTeamIndexRouteImport } from './routes/dashboard/team/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardSourcesIndexRouteImport } from './routes/dashboard/sources/index'
import { Route as DashboardSimulationsIndexRouteImport } from './routes/dashboard/simulations/index'
import { Route as DashboardRealityStreamIndexRouteImport } from './routes/dashboard/reality-stream/index'
import { Route as DashboardPatternsIndexRouteImport } from './routes/dashboard/patterns/index'
import { Route as DashboardGraphIndexRouteImport } from './routes/dashboard/graph/index'
import { Route as DashboardDecisionsIndexRouteImport } from './routes/dashboard/decisions/index'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts/index'
import { Route as DashboardCommitmentsIndexRouteImport } from './routes/dashboard/commitments/index'
import { Route as DashboardUioUioIdRouteImport } from './routes/dashboard/uio/$uioId'
import { Route as DashboardTeamSettingsRouteImport } from './routes/dashboard/team/settings'
import { Route as DashboardTeamMembersRouteImport } from './routes/dashboard/team/members'
import { Route as DashboardTeamInvitationsRouteImport } from './routes/dashboard/team/invitations'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks/$taskId'
import { Route as DashboardDecisionsDecisionIdRouteImport } from './routes/dashboard/decisions/$decisionId'
import { Route as DashboardCommitmentsCommitmentIdRouteImport } from './routes/dashboard/commitments/$commitmentId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingInviteTeamRoute = OnboardingInviteTeamRouteImport.update({
  id: '/invite-team',
  path: '/invite-team',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingCreateOrgRoute = OnboardingCreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingConnectSourcesRoute =
  OnboardingConnectSourcesRouteImport.update({
    id: '/connect-sources',
    path: '/connect-sources',
    getParentRoute: () => OnboardingRouteRoute,
  } as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const DashboardTrustRoute = DashboardTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExchangeRoute = DashboardExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContinuumsRoute = DashboardContinuumsRouteImport.update({
  id: '/continuums',
  path: '/continuums',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConsoleRoute = DashboardConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardActuationsRoute = DashboardActuationsRouteImport.update({
  id: '/actuations',
  path: '/actuations',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamIndexRoute = DashboardTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSourcesIndexRoute = DashboardSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSimulationsIndexRoute =
  DashboardSimulationsIndexRouteImport.update({
    id: '/simulations/',
    path: '/simulations/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardRealityStreamIndexRoute =
  DashboardRealityStreamIndexRouteImport.update({
    id: '/reality-stream/',
    path: '/reality-stream/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPatternsIndexRoute = DashboardPatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGraphIndexRoute = DashboardGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDecisionsIndexRoute = DashboardDecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommitmentsIndexRoute =
  DashboardCommitmentsIndexRouteImport.update({
    id: '/commitments/',
    path: '/commitments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUioUioIdRoute = DashboardUioUioIdRouteImport.update({
  id: '/uio/$uioId',
  path: '/uio/$uioId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamSettingsRoute = DashboardTeamSettingsRouteImport.update({
  id: '/team/settings',
  path: '/team/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamMembersRoute = DashboardTeamMembersRouteImport.update({
  id: '/team/members',
  path: '/team/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamInvitationsRoute =
  DashboardTeamInvitationsRouteImport.update({
    id: '/team/invitations',
    path: '/team/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDecisionsDecisionIdRoute =
  DashboardDecisionsDecisionIdRouteImport.update({
    id: '/decisions/$decisionId',
    path: '/decisions/$decisionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommitmentsCommitmentIdRoute =
  DashboardCommitmentsCommitmentIdRouteImport.update({
    id: '/commitments/$commitmentId',
    path: '/commitments/$commitmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/dashboard/actuations': typeof DashboardActuationsRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/console': typeof DashboardConsoleRoute
  '/dashboard/continuums': typeof DashboardContinuumsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trust': typeof DashboardTrustRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/decisions': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph': typeof DashboardGraphIndexRoute
  '/dashboard/patterns': typeof DashboardPatternsIndexRoute
  '/dashboard/reality-stream': typeof DashboardRealityStreamIndexRoute
  '/dashboard/simulations': typeof DashboardSimulationsIndexRoute
  '/dashboard/sources': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/dashboard/actuations': typeof DashboardActuationsRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/console': typeof DashboardConsoleRoute
  '/dashboard/continuums': typeof DashboardContinuumsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trust': typeof DashboardTrustRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/decisions': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph': typeof DashboardGraphIndexRoute
  '/dashboard/patterns': typeof DashboardPatternsIndexRoute
  '/dashboard/reality-stream': typeof DashboardRealityStreamIndexRoute
  '/dashboard/simulations': typeof DashboardSimulationsIndexRoute
  '/dashboard/sources': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/dashboard/actuations': typeof DashboardActuationsRoute
  '/dashboard/builder': typeof DashboardBuilderRoute
  '/dashboard/console': typeof DashboardConsoleRoute
  '/dashboard/continuums': typeof DashboardContinuumsRoute
  '/dashboard/exchange': typeof DashboardExchangeRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/trust': typeof DashboardTrustRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments/': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/decisions/': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph/': typeof DashboardGraphIndexRoute
  '/dashboard/patterns/': typeof DashboardPatternsIndexRoute
  '/dashboard/reality-stream/': typeof DashboardRealityStreamIndexRoute
  '/dashboard/simulations/': typeof DashboardSimulationsIndexRoute
  '/dashboard/sources/': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/actuations'
    | '/dashboard/builder'
    | '/dashboard/console'
    | '/dashboard/continuums'
    | '/dashboard/exchange'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/trust'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments'
    | '/dashboard/contacts'
    | '/dashboard/decisions'
    | '/dashboard/graph'
    | '/dashboard/patterns'
    | '/dashboard/reality-stream'
    | '/dashboard/simulations'
    | '/dashboard/sources'
    | '/dashboard/tasks'
    | '/dashboard/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/actuations'
    | '/dashboard/builder'
    | '/dashboard/console'
    | '/dashboard/continuums'
    | '/dashboard/exchange'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/trust'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments'
    | '/dashboard/contacts'
    | '/dashboard/decisions'
    | '/dashboard/graph'
    | '/dashboard/patterns'
    | '/dashboard/reality-stream'
    | '/dashboard/simulations'
    | '/dashboard/sources'
    | '/dashboard/tasks'
    | '/dashboard/team'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/dashboard/actuations'
    | '/dashboard/builder'
    | '/dashboard/console'
    | '/dashboard/continuums'
    | '/dashboard/exchange'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/trust'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments/'
    | '/dashboard/contacts/'
    | '/dashboard/decisions/'
    | '/dashboard/graph/'
    | '/dashboard/patterns/'
    | '/dashboard/reality-stream/'
    | '/dashboard/simulations/'
    | '/dashboard/sources/'
    | '/dashboard/tasks/'
    | '/dashboard/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  AiRoute: typeof AiRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding/invite-team': {
      id: '/onboarding/invite-team'
      path: '/invite-team'
      fullPath: '/onboarding/invite-team'
      preLoaderRoute: typeof OnboardingInviteTeamRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/create-org': {
      id: '/onboarding/create-org'
      path: '/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof OnboardingCreateOrgRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/connect-sources': {
      id: '/onboarding/connect-sources'
      path: '/connect-sources'
      fullPath: '/onboarding/connect-sources'
      preLoaderRoute: typeof OnboardingConnectSourcesRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/dashboard/trust': {
      id: '/dashboard/trust'
      path: '/trust'
      fullPath: '/dashboard/trust'
      preLoaderRoute: typeof DashboardTrustRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/exchange': {
      id: '/dashboard/exchange'
      path: '/exchange'
      fullPath: '/dashboard/exchange'
      preLoaderRoute: typeof DashboardExchangeRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/continuums': {
      id: '/dashboard/continuums'
      path: '/continuums'
      fullPath: '/dashboard/continuums'
      preLoaderRoute: typeof DashboardContinuumsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/console': {
      id: '/dashboard/console'
      path: '/console'
      fullPath: '/dashboard/console'
      preLoaderRoute: typeof DashboardConsoleRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/builder': {
      id: '/dashboard/builder'
      path: '/builder'
      fullPath: '/dashboard/builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/actuations': {
      id: '/dashboard/actuations'
      path: '/actuations'
      fullPath: '/dashboard/actuations'
      preLoaderRoute: typeof DashboardActuationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/': {
      id: '/dashboard/team/'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sources/': {
      id: '/dashboard/sources/'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof DashboardSourcesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/simulations/': {
      id: '/dashboard/simulations/'
      path: '/simulations'
      fullPath: '/dashboard/simulations'
      preLoaderRoute: typeof DashboardSimulationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reality-stream/': {
      id: '/dashboard/reality-stream/'
      path: '/reality-stream'
      fullPath: '/dashboard/reality-stream'
      preLoaderRoute: typeof DashboardRealityStreamIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patterns/': {
      id: '/dashboard/patterns/'
      path: '/patterns'
      fullPath: '/dashboard/patterns'
      preLoaderRoute: typeof DashboardPatternsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/graph/': {
      id: '/dashboard/graph/'
      path: '/graph'
      fullPath: '/dashboard/graph'
      preLoaderRoute: typeof DashboardGraphIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/decisions/': {
      id: '/dashboard/decisions/'
      path: '/decisions'
      fullPath: '/dashboard/decisions'
      preLoaderRoute: typeof DashboardDecisionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/commitments/': {
      id: '/dashboard/commitments/'
      path: '/commitments'
      fullPath: '/dashboard/commitments'
      preLoaderRoute: typeof DashboardCommitmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/uio/$uioId': {
      id: '/dashboard/uio/$uioId'
      path: '/uio/$uioId'
      fullPath: '/dashboard/uio/$uioId'
      preLoaderRoute: typeof DashboardUioUioIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/settings': {
      id: '/dashboard/team/settings'
      path: '/team/settings'
      fullPath: '/dashboard/team/settings'
      preLoaderRoute: typeof DashboardTeamSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/members': {
      id: '/dashboard/team/members'
      path: '/team/members'
      fullPath: '/dashboard/team/members'
      preLoaderRoute: typeof DashboardTeamMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/invitations': {
      id: '/dashboard/team/invitations'
      path: '/team/invitations'
      fullPath: '/dashboard/team/invitations'
      preLoaderRoute: typeof DashboardTeamInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/decisions/$decisionId': {
      id: '/dashboard/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/dashboard/decisions/$decisionId'
      preLoaderRoute: typeof DashboardDecisionsDecisionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/commitments/$commitmentId': {
      id: '/dashboard/commitments/$commitmentId'
      path: '/commitments/$commitmentId'
      fullPath: '/dashboard/commitments/$commitmentId'
      preLoaderRoute: typeof DashboardCommitmentsCommitmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardActuationsRoute: typeof DashboardActuationsRoute
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DashboardConsoleRoute: typeof DashboardConsoleRoute
  DashboardContinuumsRoute: typeof DashboardContinuumsRoute
  DashboardExchangeRoute: typeof DashboardExchangeRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTrustRoute: typeof DashboardTrustRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCommitmentsCommitmentIdRoute: typeof DashboardCommitmentsCommitmentIdRoute
  DashboardDecisionsDecisionIdRoute: typeof DashboardDecisionsDecisionIdRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardTeamInvitationsRoute: typeof DashboardTeamInvitationsRoute
  DashboardTeamMembersRoute: typeof DashboardTeamMembersRoute
  DashboardTeamSettingsRoute: typeof DashboardTeamSettingsRoute
  DashboardUioUioIdRoute: typeof DashboardUioUioIdRoute
  DashboardCommitmentsIndexRoute: typeof DashboardCommitmentsIndexRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardDecisionsIndexRoute: typeof DashboardDecisionsIndexRoute
  DashboardGraphIndexRoute: typeof DashboardGraphIndexRoute
  DashboardPatternsIndexRoute: typeof DashboardPatternsIndexRoute
  DashboardRealityStreamIndexRoute: typeof DashboardRealityStreamIndexRoute
  DashboardSimulationsIndexRoute: typeof DashboardSimulationsIndexRoute
  DashboardSourcesIndexRoute: typeof DashboardSourcesIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardTeamIndexRoute: typeof DashboardTeamIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardActuationsRoute: DashboardActuationsRoute,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DashboardConsoleRoute: DashboardConsoleRoute,
  DashboardContinuumsRoute: DashboardContinuumsRoute,
  DashboardExchangeRoute: DashboardExchangeRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTrustRoute: DashboardTrustRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCommitmentsCommitmentIdRoute: DashboardCommitmentsCommitmentIdRoute,
  DashboardDecisionsDecisionIdRoute: DashboardDecisionsDecisionIdRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardTeamInvitationsRoute: DashboardTeamInvitationsRoute,
  DashboardTeamMembersRoute: DashboardTeamMembersRoute,
  DashboardTeamSettingsRoute: DashboardTeamSettingsRoute,
  DashboardUioUioIdRoute: DashboardUioUioIdRoute,
  DashboardCommitmentsIndexRoute: DashboardCommitmentsIndexRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardDecisionsIndexRoute: DashboardDecisionsIndexRoute,
  DashboardGraphIndexRoute: DashboardGraphIndexRoute,
  DashboardPatternsIndexRoute: DashboardPatternsIndexRoute,
  DashboardRealityStreamIndexRoute: DashboardRealityStreamIndexRoute,
  DashboardSimulationsIndexRoute: DashboardSimulationsIndexRoute,
  DashboardSourcesIndexRoute: DashboardSourcesIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardTeamIndexRoute: DashboardTeamIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingConnectSourcesRoute: typeof OnboardingConnectSourcesRoute
  OnboardingCreateOrgRoute: typeof OnboardingCreateOrgRoute
  OnboardingInviteTeamRoute: typeof OnboardingInviteTeamRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingConnectSourcesRoute: OnboardingConnectSourcesRoute,
  OnboardingCreateOrgRoute: OnboardingCreateOrgRoute,
  OnboardingInviteTeamRoute: OnboardingInviteTeamRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  AiRoute: AiRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
