/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OnboardingInviteTeamRouteImport } from './routes/onboarding/invite-team'
import { Route as OnboardingCreateOrgRouteImport } from './routes/onboarding/create-org'
import { Route as OnboardingConnectSourcesRouteImport } from './routes/onboarding/connect-sources'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardEmailAccountsRouteImport } from './routes/dashboard/email-accounts'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAiRouteImport } from './routes/dashboard/ai'
import { Route as AdminWaitlistRouteImport } from './routes/admin/waitlist'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as DashboardTodayIndexRouteImport } from './routes/dashboard/today/index'
import { Route as DashboardTeamIndexRouteImport } from './routes/dashboard/team/index'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardSourcesIndexRouteImport } from './routes/dashboard/sources/index'
import { Route as DashboardSearchIndexRouteImport } from './routes/dashboard/search/index'
import { Route as DashboardPatternsIndexRouteImport } from './routes/dashboard/patterns/index'
import { Route as DashboardInboxIndexRouteImport } from './routes/dashboard/inbox/index'
import { Route as DashboardGraphIndexRouteImport } from './routes/dashboard/graph/index'
import { Route as DashboardDecisionsIndexRouteImport } from './routes/dashboard/decisions/index'
import { Route as DashboardContactsIndexRouteImport } from './routes/dashboard/contacts/index'
import { Route as DashboardCommitmentsIndexRouteImport } from './routes/dashboard/commitments/index'
import { Route as DashboardUioUioIdRouteImport } from './routes/dashboard/uio/$uioId'
import { Route as DashboardTeamSettingsRouteImport } from './routes/dashboard/team/settings'
import { Route as DashboardTeamMembersRouteImport } from './routes/dashboard/team/members'
import { Route as DashboardTeamInvitationsRouteImport } from './routes/dashboard/team/invitations'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks/$taskId'
import { Route as DashboardSettingsTeamsRouteImport } from './routes/dashboard/settings/teams'
import { Route as DashboardSettingsSharedInboxRouteImport } from './routes/dashboard/settings/shared-inbox'
import { Route as DashboardSettingsRolesRouteImport } from './routes/dashboard/settings/roles'
import { Route as DashboardSettingsOrganizationRouteImport } from './routes/dashboard/settings/organization'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/dashboard/settings/notifications'
import { Route as DashboardInboxSharedRouteImport } from './routes/dashboard/inbox/shared'
import { Route as DashboardDecisionsDecisionIdRouteImport } from './routes/dashboard/decisions/$decisionId'
import { Route as DashboardContactsContactIdRouteImport } from './routes/dashboard/contacts/$contactId'
import { Route as DashboardCommitmentsCommitmentIdRouteImport } from './routes/dashboard/commitments/$commitmentId'
import { Route as DashboardEmailThreadThreadIdRouteImport } from './routes/dashboard/email/thread.$threadId'

const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OnboardingInviteTeamRoute = OnboardingInviteTeamRouteImport.update({
  id: '/onboarding/invite-team',
  path: '/onboarding/invite-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateOrgRoute = OnboardingCreateOrgRouteImport.update({
  id: '/onboarding/create-org',
  path: '/onboarding/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConnectSourcesRoute =
  OnboardingConnectSourcesRouteImport.update({
    id: '/onboarding/connect-sources',
    path: '/onboarding/connect-sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailAccountsRoute = DashboardEmailAccountsRouteImport.update({
  id: '/email-accounts',
  path: '/email-accounts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardTodayIndexRoute = DashboardTodayIndexRouteImport.update({
  id: '/today/',
  path: '/today/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamIndexRoute = DashboardTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSourcesIndexRoute = DashboardSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchIndexRoute = DashboardSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPatternsIndexRoute = DashboardPatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInboxIndexRoute = DashboardInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGraphIndexRoute = DashboardGraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDecisionsIndexRoute = DashboardDecisionsIndexRouteImport.update({
  id: '/decisions/',
  path: '/decisions/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardContactsIndexRoute = DashboardContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommitmentsIndexRoute =
  DashboardCommitmentsIndexRouteImport.update({
    id: '/commitments/',
    path: '/commitments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUioUioIdRoute = DashboardUioUioIdRouteImport.update({
  id: '/uio/$uioId',
  path: '/uio/$uioId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamSettingsRoute = DashboardTeamSettingsRouteImport.update({
  id: '/team/settings',
  path: '/team/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamMembersRoute = DashboardTeamMembersRouteImport.update({
  id: '/team/members',
  path: '/team/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTeamInvitationsRoute =
  DashboardTeamInvitationsRouteImport.update({
    id: '/team/invitations',
    path: '/team/invitations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsTeamsRoute = DashboardSettingsTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSharedInboxRoute =
  DashboardSettingsSharedInboxRouteImport.update({
    id: '/shared-inbox',
    path: '/shared-inbox',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsOrganizationRoute =
  DashboardSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardInboxSharedRoute = DashboardInboxSharedRouteImport.update({
  id: '/inbox/shared',
  path: '/inbox/shared',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDecisionsDecisionIdRoute =
  DashboardDecisionsDecisionIdRouteImport.update({
    id: '/decisions/$decisionId',
    path: '/decisions/$decisionId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardContactsContactIdRoute =
  DashboardContactsContactIdRouteImport.update({
    id: '/contacts/$contactId',
    path: '/contacts/$contactId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCommitmentsCommitmentIdRoute =
  DashboardCommitmentsCommitmentIdRouteImport.update({
    id: '/commitments/$commitmentId',
    path: '/commitments/$commitmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailThreadThreadIdRoute =
  DashboardEmailThreadThreadIdRouteImport.update({
    id: '/email/thread/$threadId',
    path: '/email/thread/$threadId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/inbox/shared': typeof DashboardInboxSharedRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/shared-inbox': typeof DashboardSettingsSharedInboxRoute
  '/dashboard/settings/teams': typeof DashboardSettingsTeamsRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/decisions': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph': typeof DashboardGraphIndexRoute
  '/dashboard/inbox': typeof DashboardInboxIndexRoute
  '/dashboard/patterns': typeof DashboardPatternsIndexRoute
  '/dashboard/search': typeof DashboardSearchIndexRoute
  '/dashboard/sources': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
  '/dashboard/today': typeof DashboardTodayIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/inbox/shared': typeof DashboardInboxSharedRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/shared-inbox': typeof DashboardSettingsSharedInboxRoute
  '/dashboard/settings/teams': typeof DashboardSettingsTeamsRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts': typeof DashboardContactsIndexRoute
  '/dashboard/decisions': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph': typeof DashboardGraphIndexRoute
  '/dashboard/inbox': typeof DashboardInboxIndexRoute
  '/dashboard/patterns': typeof DashboardPatternsIndexRoute
  '/dashboard/search': typeof DashboardSearchIndexRoute
  '/dashboard/sources': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/dashboard/team': typeof DashboardTeamIndexRoute
  '/dashboard/today': typeof DashboardTodayIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/ai': typeof AiRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/email-accounts': typeof DashboardEmailAccountsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/connect-sources': typeof OnboardingConnectSourcesRoute
  '/onboarding/create-org': typeof OnboardingCreateOrgRoute
  '/onboarding/invite-team': typeof OnboardingInviteTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/dashboard/commitments/$commitmentId': typeof DashboardCommitmentsCommitmentIdRoute
  '/dashboard/contacts/$contactId': typeof DashboardContactsContactIdRoute
  '/dashboard/decisions/$decisionId': typeof DashboardDecisionsDecisionIdRoute
  '/dashboard/inbox/shared': typeof DashboardInboxSharedRoute
  '/dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/dashboard/settings/organization': typeof DashboardSettingsOrganizationRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/shared-inbox': typeof DashboardSettingsSharedInboxRoute
  '/dashboard/settings/teams': typeof DashboardSettingsTeamsRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/team/invitations': typeof DashboardTeamInvitationsRoute
  '/dashboard/team/members': typeof DashboardTeamMembersRoute
  '/dashboard/team/settings': typeof DashboardTeamSettingsRoute
  '/dashboard/uio/$uioId': typeof DashboardUioUioIdRoute
  '/dashboard/commitments/': typeof DashboardCommitmentsIndexRoute
  '/dashboard/contacts/': typeof DashboardContactsIndexRoute
  '/dashboard/decisions/': typeof DashboardDecisionsIndexRoute
  '/dashboard/graph/': typeof DashboardGraphIndexRoute
  '/dashboard/inbox/': typeof DashboardInboxIndexRoute
  '/dashboard/patterns/': typeof DashboardPatternsIndexRoute
  '/dashboard/search/': typeof DashboardSearchIndexRoute
  '/dashboard/sources/': typeof DashboardSourcesIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/dashboard/team/': typeof DashboardTeamIndexRoute
  '/dashboard/today/': typeof DashboardTodayIndexRoute
  '/dashboard/email/thread/$threadId': typeof DashboardEmailThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/admin/waitlist'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin/'
    | '/dashboard/'
    | '/onboarding'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/inbox/shared'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/shared-inbox'
    | '/dashboard/settings/teams'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments'
    | '/dashboard/contacts'
    | '/dashboard/decisions'
    | '/dashboard/graph'
    | '/dashboard/inbox'
    | '/dashboard/patterns'
    | '/dashboard/search'
    | '/dashboard/sources'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/today'
    | '/dashboard/email/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/admin/waitlist'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/inbox/shared'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/shared-inbox'
    | '/dashboard/settings/teams'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments'
    | '/dashboard/contacts'
    | '/dashboard/decisions'
    | '/dashboard/graph'
    | '/dashboard/inbox'
    | '/dashboard/patterns'
    | '/dashboard/search'
    | '/dashboard/sources'
    | '/dashboard/tasks'
    | '/dashboard/team'
    | '/dashboard/today'
    | '/dashboard/email/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/ai'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/success'
    | '/verify-2fa'
    | '/admin/audit'
    | '/admin/organizations'
    | '/admin/users'
    | '/admin/waitlist'
    | '/dashboard/ai'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/email-accounts'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/onboarding/complete'
    | '/onboarding/connect-sources'
    | '/onboarding/create-org'
    | '/onboarding/invite-team'
    | '/admin/'
    | '/dashboard/'
    | '/onboarding/'
    | '/dashboard/commitments/$commitmentId'
    | '/dashboard/contacts/$contactId'
    | '/dashboard/decisions/$decisionId'
    | '/dashboard/inbox/shared'
    | '/dashboard/settings/notifications'
    | '/dashboard/settings/organization'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/shared-inbox'
    | '/dashboard/settings/teams'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/team/invitations'
    | '/dashboard/team/members'
    | '/dashboard/team/settings'
    | '/dashboard/uio/$uioId'
    | '/dashboard/commitments/'
    | '/dashboard/contacts/'
    | '/dashboard/decisions/'
    | '/dashboard/graph/'
    | '/dashboard/inbox/'
    | '/dashboard/patterns/'
    | '/dashboard/search/'
    | '/dashboard/sources/'
    | '/dashboard/tasks/'
    | '/dashboard/team/'
    | '/dashboard/today/'
    | '/dashboard/email/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AiRoute: typeof AiRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  Verify2faRoute: typeof Verify2faRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingConnectSourcesRoute: typeof OnboardingConnectSourcesRoute
  OnboardingCreateOrgRoute: typeof OnboardingCreateOrgRoute
  OnboardingInviteTeamRoute: typeof OnboardingInviteTeamRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/onboarding/invite-team': {
      id: '/onboarding/invite-team'
      path: '/onboarding/invite-team'
      fullPath: '/onboarding/invite-team'
      preLoaderRoute: typeof OnboardingInviteTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/create-org': {
      id: '/onboarding/create-org'
      path: '/onboarding/create-org'
      fullPath: '/onboarding/create-org'
      preLoaderRoute: typeof OnboardingCreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/connect-sources': {
      id: '/onboarding/connect-sources'
      path: '/onboarding/connect-sources'
      fullPath: '/onboarding/connect-sources'
      preLoaderRoute: typeof OnboardingConnectSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email-accounts': {
      id: '/dashboard/email-accounts'
      path: '/email-accounts'
      fullPath: '/dashboard/email-accounts'
      preLoaderRoute: typeof DashboardEmailAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/today/': {
      id: '/dashboard/today/'
      path: '/today'
      fullPath: '/dashboard/today'
      preLoaderRoute: typeof DashboardTodayIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/': {
      id: '/dashboard/team/'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sources/': {
      id: '/dashboard/sources/'
      path: '/sources'
      fullPath: '/dashboard/sources'
      preLoaderRoute: typeof DashboardSourcesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/search/': {
      id: '/dashboard/search/'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/patterns/': {
      id: '/dashboard/patterns/'
      path: '/patterns'
      fullPath: '/dashboard/patterns'
      preLoaderRoute: typeof DashboardPatternsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inbox/': {
      id: '/dashboard/inbox/'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/graph/': {
      id: '/dashboard/graph/'
      path: '/graph'
      fullPath: '/dashboard/graph'
      preLoaderRoute: typeof DashboardGraphIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/decisions/': {
      id: '/dashboard/decisions/'
      path: '/decisions'
      fullPath: '/dashboard/decisions'
      preLoaderRoute: typeof DashboardDecisionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/': {
      id: '/dashboard/contacts/'
      path: '/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/commitments/': {
      id: '/dashboard/commitments/'
      path: '/commitments'
      fullPath: '/dashboard/commitments'
      preLoaderRoute: typeof DashboardCommitmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/uio/$uioId': {
      id: '/dashboard/uio/$uioId'
      path: '/uio/$uioId'
      fullPath: '/dashboard/uio/$uioId'
      preLoaderRoute: typeof DashboardUioUioIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/settings': {
      id: '/dashboard/team/settings'
      path: '/team/settings'
      fullPath: '/dashboard/team/settings'
      preLoaderRoute: typeof DashboardTeamSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/members': {
      id: '/dashboard/team/members'
      path: '/team/members'
      fullPath: '/dashboard/team/members'
      preLoaderRoute: typeof DashboardTeamMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/team/invitations': {
      id: '/dashboard/team/invitations'
      path: '/team/invitations'
      fullPath: '/dashboard/team/invitations'
      preLoaderRoute: typeof DashboardTeamInvitationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/teams': {
      id: '/dashboard/settings/teams'
      path: '/teams'
      fullPath: '/dashboard/settings/teams'
      preLoaderRoute: typeof DashboardSettingsTeamsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/shared-inbox': {
      id: '/dashboard/settings/shared-inbox'
      path: '/shared-inbox'
      fullPath: '/dashboard/settings/shared-inbox'
      preLoaderRoute: typeof DashboardSettingsSharedInboxRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/roles': {
      id: '/dashboard/settings/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/organization': {
      id: '/dashboard/settings/organization'
      path: '/organization'
      fullPath: '/dashboard/settings/organization'
      preLoaderRoute: typeof DashboardSettingsOrganizationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/notifications': {
      id: '/dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/dashboard/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/inbox/shared': {
      id: '/dashboard/inbox/shared'
      path: '/inbox/shared'
      fullPath: '/dashboard/inbox/shared'
      preLoaderRoute: typeof DashboardInboxSharedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/decisions/$decisionId': {
      id: '/dashboard/decisions/$decisionId'
      path: '/decisions/$decisionId'
      fullPath: '/dashboard/decisions/$decisionId'
      preLoaderRoute: typeof DashboardDecisionsDecisionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/contacts/$contactId': {
      id: '/dashboard/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/dashboard/contacts/$contactId'
      preLoaderRoute: typeof DashboardContactsContactIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/commitments/$commitmentId': {
      id: '/dashboard/commitments/$commitmentId'
      path: '/commitments/$commitmentId'
      fullPath: '/dashboard/commitments/$commitmentId'
      preLoaderRoute: typeof DashboardCommitmentsCommitmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/thread/$threadId': {
      id: '/dashboard/email/thread/$threadId'
      path: '/email/thread/$threadId'
      fullPath: '/dashboard/email/thread/$threadId'
      preLoaderRoute: typeof DashboardEmailThreadThreadIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardSettingsRouteChildren {
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsOrganizationRoute: typeof DashboardSettingsOrganizationRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsSharedInboxRoute: typeof DashboardSettingsSharedInboxRoute
  DashboardSettingsTeamsRoute: typeof DashboardSettingsTeamsRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsOrganizationRoute: DashboardSettingsOrganizationRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsSharedInboxRoute: DashboardSettingsSharedInboxRoute,
  DashboardSettingsTeamsRoute: DashboardSettingsTeamsRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardEmailAccountsRoute: typeof DashboardEmailAccountsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCommitmentsCommitmentIdRoute: typeof DashboardCommitmentsCommitmentIdRoute
  DashboardContactsContactIdRoute: typeof DashboardContactsContactIdRoute
  DashboardDecisionsDecisionIdRoute: typeof DashboardDecisionsDecisionIdRoute
  DashboardInboxSharedRoute: typeof DashboardInboxSharedRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardTeamInvitationsRoute: typeof DashboardTeamInvitationsRoute
  DashboardTeamMembersRoute: typeof DashboardTeamMembersRoute
  DashboardTeamSettingsRoute: typeof DashboardTeamSettingsRoute
  DashboardUioUioIdRoute: typeof DashboardUioUioIdRoute
  DashboardCommitmentsIndexRoute: typeof DashboardCommitmentsIndexRoute
  DashboardContactsIndexRoute: typeof DashboardContactsIndexRoute
  DashboardDecisionsIndexRoute: typeof DashboardDecisionsIndexRoute
  DashboardGraphIndexRoute: typeof DashboardGraphIndexRoute
  DashboardInboxIndexRoute: typeof DashboardInboxIndexRoute
  DashboardPatternsIndexRoute: typeof DashboardPatternsIndexRoute
  DashboardSearchIndexRoute: typeof DashboardSearchIndexRoute
  DashboardSourcesIndexRoute: typeof DashboardSourcesIndexRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
  DashboardTeamIndexRoute: typeof DashboardTeamIndexRoute
  DashboardTodayIndexRoute: typeof DashboardTodayIndexRoute
  DashboardEmailThreadThreadIdRoute: typeof DashboardEmailThreadThreadIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardEmailAccountsRoute: DashboardEmailAccountsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCommitmentsCommitmentIdRoute: DashboardCommitmentsCommitmentIdRoute,
  DashboardContactsContactIdRoute: DashboardContactsContactIdRoute,
  DashboardDecisionsDecisionIdRoute: DashboardDecisionsDecisionIdRoute,
  DashboardInboxSharedRoute: DashboardInboxSharedRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardTeamInvitationsRoute: DashboardTeamInvitationsRoute,
  DashboardTeamMembersRoute: DashboardTeamMembersRoute,
  DashboardTeamSettingsRoute: DashboardTeamSettingsRoute,
  DashboardUioUioIdRoute: DashboardUioUioIdRoute,
  DashboardCommitmentsIndexRoute: DashboardCommitmentsIndexRoute,
  DashboardContactsIndexRoute: DashboardContactsIndexRoute,
  DashboardDecisionsIndexRoute: DashboardDecisionsIndexRoute,
  DashboardGraphIndexRoute: DashboardGraphIndexRoute,
  DashboardInboxIndexRoute: DashboardInboxIndexRoute,
  DashboardPatternsIndexRoute: DashboardPatternsIndexRoute,
  DashboardSearchIndexRoute: DashboardSearchIndexRoute,
  DashboardSourcesIndexRoute: DashboardSourcesIndexRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
  DashboardTeamIndexRoute: DashboardTeamIndexRoute,
  DashboardTodayIndexRoute: DashboardTodayIndexRoute,
  DashboardEmailThreadThreadIdRoute: DashboardEmailThreadThreadIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AiRoute: AiRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  Verify2faRoute: Verify2faRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingConnectSourcesRoute: OnboardingConnectSourcesRoute,
  OnboardingCreateOrgRoute: OnboardingCreateOrgRoute,
  OnboardingInviteTeamRoute: OnboardingInviteTeamRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
