platform :ios do
  desc "Build iOS app"
  lane :build do
    sh "bash /Users/jeremyscatigna/project-memory/scripts/generate_apple_projects.sh"
    sh "bash /Users/jeremyscatigna/project-memory/scripts/build_ios.sh"
  end
end
