apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drovi

resources:
  - storageclass.gp3.yaml
  - namespace.yaml
  - configmap.yaml
  - serviceaccounts.yaml
  - falkordb.statefulset.yaml
  - nats.statefulset.yaml
  - drovi-intelligence-api.yaml
  - drovi-workers.yaml
  - imperium-api-workers.yaml
  - web-admin-imperium-web.yaml
  - poddisruptionbudgets.yaml
  - hpa.yaml
  - ingress.yaml
