"use client";

import { useMutation, useQuery } from "@tanstack/react-query";
import {
  Bell,
  BookOpen,
  Calendar,
  CheckCircle2,
  Loader2,
  Mail,
  Moon,
} from "lucide-react";
import { toast } from "sonner";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";
import { queryClient, useTRPC } from "@/utils/trpc";

// =============================================================================
// NOTIFICATION SETTINGS COMPONENT
// =============================================================================

export function NotificationSettings() {
  const trpc = useTRPC();

  const { data: preferences, isLoading } = useQuery(
    trpc.notifications.getPreferences.queryOptions()
  );

  const updateMutation = useMutation({
    ...trpc.notifications.updatePreferences.mutationOptions(),
    onSuccess: () => {
      queryClient.invalidateQueries({
        queryKey: [["notifications", "getPreferences"]],
      });
      toast.success("Notification preferences updated");
    },
    onError: () => {
      toast.error("Failed to update preferences");
    },
  });

  const updatePreference = (key: string, value: boolean | string) => {
    updateMutation.mutate({ [key]: value });
  };

  if (isLoading) {
    return (
      <Card>
        <CardContent className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <Bell className="h-5 w-5 text-primary" />
          <CardTitle>Notification Preferences</CardTitle>
        </div>
        <CardDescription>
          Control how and when you receive notifications from Drovi
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-8">
        {/* Delivery Channels */}
        <section className="space-y-4">
          <h3 className="font-medium text-sm">Delivery Channels</h3>
          <div className="space-y-4">
            <ToggleRow
              checked={preferences?.inAppEnabled ?? true}
              description="Show notifications in the notification center"
              disabled={updateMutation.isPending}
              label="In-app notifications"
              onCheckedChange={(checked) =>
                updatePreference("inAppEnabled", checked)
              }
            />
            <div className="flex items-center justify-between">
              <div>
                <Label>Email digest</Label>
                <p className="text-muted-foreground text-xs">
                  Receive summary emails of your notifications
                </p>
              </div>
              <Select
                disabled={updateMutation.isPending}
                onValueChange={(value) =>
                  updatePreference("emailDigestFrequency", value)
                }
                value={preferences?.emailDigestFrequency ?? "daily"}
              >
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="realtime">Real-time</SelectItem>
                  <SelectItem value="daily">Daily</SelectItem>
                  <SelectItem value="weekly">Weekly</SelectItem>
                  <SelectItem value="never">Never</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </section>

        <Separator />

        {/* Intelligence Notifications */}
        <section className="space-y-4">
          <div>
            <h3 className="font-medium text-sm">Intelligence Alerts</h3>
            <p className="text-muted-foreground text-xs">
              Notifications generated by Drovi AI analysis
            </p>
          </div>

          {/* Commitments */}
          <CategorySection
            icon={CheckCircle2}
            iconColor="text-blue-500"
            title="Commitments"
          >
            <ToggleRow
              checked={preferences?.commitmentsNewEnabled ?? true}
              description="When AI identifies a new commitment from your emails"
              disabled={updateMutation.isPending}
              label="New commitments extracted"
              onCheckedChange={(checked) =>
                updatePreference("commitmentsNewEnabled", checked)
              }
            />
            <ToggleRow
              checked={preferences?.commitmentsDueEnabled ?? true}
              description="Reminders before commitment due dates"
              disabled={updateMutation.isPending}
              label="Due date reminders"
              onCheckedChange={(checked) =>
                updatePreference("commitmentsDueEnabled", checked)
              }
            />
            <ToggleRow
              checked={preferences?.commitmentsOverdueEnabled ?? true}
              description="Notifications when commitments become overdue"
              disabled={updateMutation.isPending}
              label="Overdue alerts"
              onCheckedChange={(checked) =>
                updatePreference("commitmentsOverdueEnabled", checked)
              }
            />
          </CategorySection>

          {/* Decisions */}
          <CategorySection
            icon={BookOpen}
            iconColor="text-purple-500"
            title="Decisions"
          >
            <ToggleRow
              checked={preferences?.decisionsNewEnabled ?? true}
              description="When AI identifies a new decision from your emails"
              disabled={updateMutation.isPending}
              label="New decisions recorded"
              onCheckedChange={(checked) =>
                updatePreference("decisionsNewEnabled", checked)
              }
            />
            <ToggleRow
              checked={preferences?.decisionsSupersededEnabled ?? true}
              description="When a new decision replaces a previous one"
              disabled={updateMutation.isPending}
              label="Superseded decision alerts"
              onCheckedChange={(checked) =>
                updatePreference("decisionsSupersededEnabled", checked)
              }
            />
          </CategorySection>

          {/* Calendar */}
          <CategorySection
            icon={Calendar}
            iconColor="text-orange-500"
            title="Calendar"
          >
            <ToggleRow
              checked={preferences?.calendarRemindersEnabled ?? true}
              description="Reminders for upcoming calendar events"
              disabled={updateMutation.isPending}
              label="Event reminders"
              onCheckedChange={(checked) =>
                updatePreference("calendarRemindersEnabled", checked)
              }
            />
          </CategorySection>

          {/* Email Intelligence */}
          <CategorySection
            icon={Mail}
            iconColor="text-green-500"
            title="Email Intelligence"
          >
            <ToggleRow
              checked={preferences?.emailUrgentEnabled ?? true}
              description="Notifications for emails marked as urgent"
              disabled={updateMutation.isPending}
              label="Urgent emails"
              onCheckedChange={(checked) =>
                updatePreference("emailUrgentEnabled", checked)
              }
            />
            <ToggleRow
              checked={preferences?.emailImportantEnabled ?? true}
              description="Notifications for high-importance emails"
              disabled={updateMutation.isPending}
              label="Important emails"
              onCheckedChange={(checked) =>
                updatePreference("emailImportantEnabled", checked)
              }
            />
          </CategorySection>
        </section>

        <Separator />

        {/* Quiet Hours */}
        <section className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Moon className="h-4 w-4 text-muted-foreground" />
              <div>
                <h3 className="font-medium text-sm">Quiet Hours</h3>
                <p className="text-muted-foreground text-xs">
                  Pause notifications during specific times
                </p>
              </div>
            </div>
            <Switch
              checked={preferences?.quietHoursEnabled ?? false}
              disabled={updateMutation.isPending}
              onCheckedChange={(checked) =>
                updatePreference("quietHoursEnabled", checked)
              }
            />
          </div>

          {preferences?.quietHoursEnabled && (
            <div className="ml-6 grid gap-4 sm:grid-cols-3">
              <div className="space-y-2">
                <Label htmlFor="quiet-start">Start</Label>
                <Input
                  disabled={updateMutation.isPending}
                  id="quiet-start"
                  onChange={(e) =>
                    updatePreference("quietHoursStart", e.target.value)
                  }
                  type="time"
                  value={preferences?.quietHoursStart ?? "22:00"}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="quiet-end">End</Label>
                <Input
                  disabled={updateMutation.isPending}
                  id="quiet-end"
                  onChange={(e) =>
                    updatePreference("quietHoursEnd", e.target.value)
                  }
                  type="time"
                  value={preferences?.quietHoursEnd ?? "08:00"}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="quiet-timezone">Timezone</Label>
                <Select
                  disabled={updateMutation.isPending}
                  onValueChange={(value) =>
                    updatePreference("quietHoursTimezone", value)
                  }
                  value={
                    preferences?.quietHoursTimezone ??
                    Intl.DateTimeFormat().resolvedOptions().timeZone
                  }
                >
                  <SelectTrigger id="quiet-timezone">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="America/New_York">
                      Eastern (ET)
                    </SelectItem>
                    <SelectItem value="America/Chicago">
                      Central (CT)
                    </SelectItem>
                    <SelectItem value="America/Denver">
                      Mountain (MT)
                    </SelectItem>
                    <SelectItem value="America/Los_Angeles">
                      Pacific (PT)
                    </SelectItem>
                    <SelectItem value="Europe/London">London (GMT)</SelectItem>
                    <SelectItem value="Europe/Paris">Paris (CET)</SelectItem>
                    <SelectItem value="Asia/Tokyo">Tokyo (JST)</SelectItem>
                    <SelectItem value="Australia/Sydney">
                      Sydney (AEST)
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}
        </section>
      </CardContent>
    </Card>
  );
}

// =============================================================================
// HELPER COMPONENTS
// =============================================================================

interface ToggleRowProps {
  label: string;
  description?: string;
  checked: boolean;
  onCheckedChange: (checked: boolean) => void;
  disabled?: boolean;
}

function ToggleRow({
  label,
  description,
  checked,
  onCheckedChange,
  disabled,
}: ToggleRowProps) {
  return (
    <div className="flex items-center justify-between">
      <div>
        <Label>{label}</Label>
        {description && (
          <p className="text-muted-foreground text-xs">{description}</p>
        )}
      </div>
      <Switch
        checked={checked}
        disabled={disabled}
        onCheckedChange={onCheckedChange}
      />
    </div>
  );
}

interface CategorySectionProps {
  icon: typeof CheckCircle2;
  iconColor: string;
  title: string;
  children: React.ReactNode;
}

function CategorySection({
  icon: Icon,
  iconColor,
  title,
  children,
}: CategorySectionProps) {
  return (
    <div className="rounded-lg border p-4">
      <div className="mb-4 flex items-center gap-2">
        <Icon className={cn("h-4 w-4", iconColor)} />
        <span className="font-medium text-sm">{title}</span>
      </div>
      <div className="ml-6 space-y-4">{children}</div>
    </div>
  );
}

export default NotificationSettings;
