apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: configmap.patch.yaml
  - path: ingress.patch.yaml
  - path: rollout-strategy.patch.yaml
  - path: resources.patch.yaml
  - path: falkordb.resources.patch.yaml
  - path: world-brain.replicas.patch.yaml
  - path: world-brain.hpa.patch.yaml
  - path: world-brain.rollout-strategy.patch.yaml
