// This file is auto-generated by scripts/imperium/generate_api_types.py.
// Do not edit manually.

export type AddWatchlistEntryRequest = {
  label: string;
  symbol: string;
};

export type AlertEventView = {
  alert_id: string;
  category: string;
  created_at: string;
  dedupe_key: string;
  title: string;
  what_happened: string;
  what_to_watch_next: string;
  why_it_matters: string;
};

export type AlertRuleView = {
  category: string;
  cooldown_seconds: number;
  enabled: boolean;
  name: string;
  rule_id: string;
  threshold: number;
};

export type AlertSimulationRequest = {
  category: string;
  target: string;
  threshold: number;
};

export type AlertSimulationResponse = {
  dedupe_key: string;
  explanation: string;
  should_trigger: boolean;
};

export type ApiAuditEventsResponse = {
  events: Array<AuditEventView>;
};

export type ApiDeadLetterResponse = {
  events: Array<DeadLetterEventView>;
};

export type ApiHealthResponse = {
  service: string;
  status: string;
};

export type ApiMetaResponse = {
  data_mode: string;
  environment: string;
  name: string;
  providers: Array<ProviderConfigView>;
  version: string;
};

export type ApiProvidersHealthResponse = {
  checked_at: string;
  checks: Array<ProviderHealthView>;
  mode: string;
};

export type ApiProvidersResponse = {
  mode: string;
  providers: Array<ProviderConfigView>;
};

export type ApiReadinessResponse = {
  ready: boolean;
};

export type AppleVerifyRequest = {
  identity_token: string;
};

export type AppleVerifyResponse = {
  email?: string | null;
  expires_at: string;
  issued_at: string;
  subject: string;
};

export type AuditEventView = {
  action: string;
  actor_user_id?: string | null;
  created_at: string;
  event_id: string;
  metadata: string;
  payload_hash: string;
  stream_key: string;
  target: string;
};

export type BriefCitationView = {
  source_snippet: string;
  source_url: string;
};

export type BriefClaimView = {
  citations: Array<BriefCitationView>;
  confidence_score: number;
  impact_score: number;
  recommended_action?: string | null;
  statement: string;
};

export type BriefPreviewRequest = {
  key_events?: Array<string> | null;
  timezone?: string | null;
  user_id?: string | null;
  watchlist?: Array<string> | null;
};

export type BriefSectionView = {
  claims: Array<BriefClaimView>;
  section_key: string;
  summary: string;
  title: string;
};

export type BusinessAnomalyView = {
  message: string;
  metric_key: string;
  recommended_action: string;
  severity: string;
};

export type BusinessMetricView = {
  key: string;
  value: number;
  window: string;
};

export type BusinessOverviewView = {
  as_of: string;
  burn: number;
  cash_balance: number;
  entity_name: string;
  mrr: number;
  overdue_invoices: number;
  runway_months: number;
};

export type CandleView = {
  close: number;
  end_time: string;
  high: number;
  interval: string;
  low: number;
  open: number;
  start_time: string;
  symbol: string;
  volume: number;
};

export type CreatePlaybookRequest = {
  enabled?: boolean | null;
  response_steps: Array<string>;
  title: string;
  trigger: string;
};

export type CreateThesisRequest = {
  conviction_percent?: number | null;
  invalidation_criteria?: string | null;
  position?: string | null;
  review_date?: string | null;
  title: string;
};

export type DailyBriefView = {
  brief_date: string;
  brief_id: string;
  generated_at: string;
  required_reads: Array<string>;
  sections: Array<BriefSectionView>;
  user_id: string;
};

export type DeadLetterEventView = {
  created_at: string;
  error_message: string;
  event_id: string;
  first_failed_at: string;
  last_failed_at: string;
  payload: string;
  replayed_at?: string | null;
  replayed_by?: string | null;
  retry_count: number;
  status: string;
  subject: string;
  updated_at: string;
  worker_role: string;
};

export type ExposureView = {
  bucket: string;
  weight_percent: number;
};

export type InboxItemView = {
  canonical_url: string;
  cluster_key: string;
  impact_score: number;
  source_count: number;
  summary: string;
  title: string;
};

export type IngestPreviewArticleInput = {
  body?: string | null;
  published_at: string;
  source: string;
  title: string;
  url: string;
};

export type IngestPreviewRequest = {
  articles: Array<IngestPreviewArticleInput>;
};

export type IngestPreviewResponse = {
  accepted_articles: number;
  clusters: Array<StoryClusterView>;
  rejected_articles: number;
};

export type IssueSessionRequest = {
  device_id: string;
  ttl_seconds?: number | null;
  user_id: string;
};

export type IssueSessionResponse = {
  device_id: string;
  expires_at: string;
  session_id: string;
  token: string;
  user_id: string;
};

export type MacroIndicatorView = {
  change: number;
  key: string;
  updated_at: string;
  value: number;
};

export type MarketQuoteView = {
  change_percent: number;
  price: number;
  symbol: string;
  timestamp: string;
  volume: number;
};

export type MarketWatchlistItemView = {
  label: string;
  symbol: string;
};

export type PasskeyChallengeRequest = {
  rp_id?: string | null;
  ttl_seconds?: number | null;
  user_id: string;
};

export type PasskeyChallengeResponse = {
  challenge: string;
  challenge_id: string;
  expires_at: string;
  rp_id: string;
};

export type PlaybookView = {
  created_at: string;
  enabled: boolean;
  playbook_id: string;
  response_steps: Array<string>;
  title: string;
  trigger: string;
};

export type PortfolioAccountView = {
  account_id: string;
  account_type: string;
  balance: number;
  name: string;
};

export type PortfolioOverviewView = {
  accounts: Array<PortfolioAccountView>;
  as_of: string;
  daily_change: number;
  exposures: Array<ExposureView>;
  net_worth: number;
  risk_score: number;
  top_positions: Array<PortfolioPositionView>;
  ytd_change: number;
};

export type PortfolioPositionView = {
  asset_class: string;
  market_value: number;
  quantity: number;
  symbol: string;
};

export type ProviderConfigView = {
  configured: boolean;
  domain: string;
  fallbacks: Array<string>;
  primary: string;
  required_credentials: Array<string>;
};

export type ProviderHealthView = {
  details: string;
  domain: string;
  healthy: boolean;
  provider: string;
};

export type RefreshSessionRequest = {
  session_token: string;
  ttl_seconds?: number | null;
};

export type RefreshSessionResponse = {
  expires_at: string;
  session_id: string;
  token: string;
};

export type RegimeStateView = {
  confidence: number;
  explanation: string;
  regime: string;
  updated_at: string;
};

export type ReminderView = {
  review_date: string;
  thesis_id: string;
  title: string;
};

export type ReplayDeadLetterResponse = {
  event_id: string;
  replayed: boolean;
  retry_count: number;
  status: string;
  subject: string;
};

export type RevokeSessionRequest = {
  session_token: string;
};

export type RiskSignalView = {
  created_at: string;
  description: string;
  key: string;
  severity: string;
};

export type ScenarioPreviewRequest = {
  label: string;
};

export type ScenarioPreviewResponse = {
  estimated_pnl_impact: number;
  hedge_size: number;
  label: string;
  liquidity_impact: number;
};

export type ScenarioRequest = {
  fx_shock_percent: number;
  market_drop_percent: number;
  rate_spike_bps: number;
  scenario_name: string;
};

export type ScenarioResponse = {
  estimated_loss: number;
  hedge_notional: number;
  liquidity_impact: number;
  scenario_name: string;
};

export type SinceLastView = {
  items: Array<string>;
};

export type StoryClusterView = {
  article_count: number;
  canonical_url: string;
  cluster_key: string;
  impact_score: number;
  title: string;
};

export type StreamContractView = {
  channel: string;
  payload_schema: string;
  subject: string;
};

export type ThesisMutationResponse = {
  archived: boolean;
  thesis_id: string;
};

export type ThesisView = {
  conviction_percent: number;
  created_at: string;
  invalidation_criteria: string;
  position: string;
  rationale: string;
  review_date: string;
  thesis_id: string;
  title: string;
};

export type TogglePlaybookRequest = {
  enabled: boolean;
};

export type WatchlistMutationResponse = {
  label?: string | null;
  mutated: boolean;
  symbol: string;
};
